### ISSUE TITLE
DDP Bitrate Issue

### ISSUE THREAD

**Issue by alando22** [jlw4049/DeeZy#33]
If I encode a Dolby Digital Plus 5.1 audiofile with a bitrate <384 kbit/s the produced file has always 384 kbit/s. Above 384 kbit/s everything is fine.
For example: I configure a bitrate of 320 kbit/s an the new file has a bitrate 384 kbit/s.

**Comment by jlw4049** [comment]
Interesting, I'll take a look at this and get back to you.

**Comment by jlw4049** [comment]
I was able to replicate the bug. Turns out it existed when the user didn't pass the desired channel in as part of the arguments. This will be fixed in the next release coming. Thanks for the bug report! Here is the fixed version, I won't have the full release out until tomorrow sometime, but in the mean time you can use this as it is stable.

windows:
[deezy_pre.zip](https://github.com/jlw4049/DeeZy/files/14106927/deezy_pre.zip)
linux:
[deezy_pre_linux.zip](https://github.com/jlw4049/DeeZy/files/14106936/deezy_pre_linux.zip)
